apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mmssearch
  namespace: default
  labels:
    name: mmssearch
    app: jpetstore
    serviceKind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      namespace: default
      chartURL:
---
apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: modernpets
  namespace: default
  labels:
    name: modernpets
    app: jpetstore
    serviceKind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      namespace: default
      chartURL: 
