# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:  build-15.pure.mel.lab:8500/jpetstore
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - build-15.pure.mel.lab
