# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: build-15.pure.mel.lab:8500/default # Ex: us.icr.io/mynamespace
  pullPolicy: Always
  pullSecret: ""

ingress:
  enabled: true
  hosts:
    - jpetstore.10.1.11.15.nip.io # Ex: jpetstore.myclustername.us-south.containers.mybluemix.net
