# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: build-15.pure.mel.lab:8500/jpetstore
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - jpetstore.10.1.11.15.nip.io
